<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="roboML" nsURI="http://www.example.org/roboML" nsPrefix="roboML">
  <eClassifiers xsi:type="ecore:EClass" name="Unit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//UnitMeasure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnitMeasure">
    <eLiterals name="m"/>
    <eLiterals name="dm" value="1"/>
    <eLiterals name="cm" value="2"/>
    <eLiterals name="mm" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="forward" literal="forward"/>
    <eLiterals name="backward" value="1"/>
    <eLiterals name="sideLeft" value="2"/>
    <eLiterals name="sideRight" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Deplacement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="unit" lowerBound="1" eType="#//Unit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deplacementDistance" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="movementType" eType="#//Direction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rotation" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rotationAngle" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rotationSens" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booleanExpression" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instruction" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newAttribute" eType="#//RMLObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="#//RMLObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" eType="#//RMLObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableValue" eType="#//RMLObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableref" upperBound="-1"
        eType="#//VariableRef" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Assignement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="assignableVariable" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sensorValue" eType="#//RMLObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="getSensorValue" eType="#//GetValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass12"/>
  <eClassifiers xsi:type="ecore:EClass" name="DistanceSensor" eSuperTypes="#//Sensor"/>
  <eClassifiers xsi:type="ecore:EClass" name="SetValue" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entityToSet" lowerBound="1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Speed">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deplacementSpeed" eType="#//RMLObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="setSpeedValue" lowerBound="1"
        eType="#//SetValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" lowerBound="1"
        eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementIf" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementElse" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="booleanExpression" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoboMLProgram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" upperBound="-1"
        eType="#//Function" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticExpression" eSuperTypes="#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//Variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementA" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementB" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arithmeticOperator" eType="#//ArithmeticOperators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RMLObject">
    <eLiterals name="RMLInt"/>
    <eLiterals name="RMLString" value="1"/>
    <eLiterals name="RMLFloat" value="2"/>
    <eLiterals name="RMLDouble" value="3"/>
    <eLiterals name="RMLBoolean" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="entityType" eType="#//RMLObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetValue" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticOperators">
    <eLiterals name="Plus"/>
    <eLiterals name="Minus" value="1"/>
    <eLiterals name="Multiplie" value="2"/>
    <eLiterals name="Divide" value="3"/>
    <eLiterals name="Modulo" value="4"/>
    <eLiterals name="Power" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementA" lowerBound="1"
        eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementB" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="booleanOperator" eType="#//BooleanOperators"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BooleanOperators">
    <eLiterals name="Inferior"/>
    <eLiterals name="InferiorEq" value="1"/>
    <eLiterals name="Equals" value="2"/>
    <eLiterals name="Superior" value="3"/>
    <eLiterals name="SuperiorEq" value="4"/>
    <eLiterals name="Different" value="5"/>
    <eLiterals name="And" value="6"/>
    <eLiterals name="Or" value="7"/>
  </eClassifiers>
</ecore:EPackage>
